# ======================
# 基础
# ======================
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# ======================
# 启发式压缩
# ======================
use_small_heuristics = "Max"

# ======================
# 函数 / 调用
# ======================
fn_params_layout = "Tall"
chain_width = 80
single_line_if_else_max_width = 80
struct_variant_width = 35

# ======================
# imports
# ======================
reorder_imports = true
reorder_modules = true

# ======================
# match
# ======================
match_block_trailing_comma = true

# ======================
# 表达式
# ======================
remove_nested_parens = true

# ======================
# 字段 & ?
# ======================
use_field_init_shorthand = true
use_try_shorthand = true
